import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/auth-provider";
import LenisProvider from "@/providers/lenis-provider";
import { Toaster } from "@/components/ui/sonner";
import ConditionalNavbar from "@/components/home/ConditionalNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <LenisProvider>
            <ConditionalNavbar>{children}</ConditionalNavbar>
          </LenisProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
